- name: Installing nginx
  become: yes
  yum: name=nginx state=present
  notify: Restart nginx
  
- name: run service on port
  become: yes 
  template:
    src: nginx.conf
    dest: /etc/nginx/conf.d/default.conf        
  notify: Restart nginx

- name: start and run nginx as a background process
  become: yes
  service:
    name: nginx
    state: started
    enabled: yes