- name: Installing nginx
  become: yes
  yum: name=nginx state=present
  notify: Restart nginx

- name: run service on port
  become: yes 
  template:
    src: nginx.conf
    dest: /etc/nginx/conf.d/default.conf        
  register: nginx_conf_update_result

- set_fact:
    nginx_conf_update: "{{nginx_conf_update_result.changed}}"

- name: Restart nginx
  service: name=nginx state=restarted enabled=yes
  when: nginx_conf_update

- name: start and run nginx as a background process
  become: yes
  service:
    name: nginx
    state: started
    enabled: yes  