---
- hosts: webservers,webservers2
  tasks:
    - name: Adding node to yum repository
      become: yes
      yum_repository:
        name: node
        description: using from node repo
        baseurl: https://rpm.nodesource.com/pub_7.x/el/6/x86_64/
        gpgcheck: no

- hosts: webservers
  tasks:
    - name: Installing nginx and nodejs
      become: yes
      yum: name={{item}} state=present
      with_items:
        - nginx
        - nodejs-7.10.0

    - name: run service on port
      copy:
        src: ./default.conf
        dest: /etc/nginx/conf.d/default.conf        
      become: yes

    - name: restart and run nginx as a background process
      become: yes
      service:
        name: nginx
        state: restarted
        enabled: yes

- hosts: webservers2
  tasks:
    - name : Installing nodejs
      become: yes
      yum:
        name: nodejs-7.9.0
        state: present
